name: Terraform apply

on:
  pull_request:
    types:
      - closed
    branches:
      - $default-branch
    paths:
      - '**.tf'

env:
  DEPLOYMENT_ROLE_TO_ASSUME: arn:aws:iam::$TARGET_AWS_ACCOUNT_ID:role/$TARGET_DEPLYOMENT_ROLE
  AWS_REGION: $TARGET_REGION

jobs:
  apply:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: self-hosted
    strategy:
      # Disable fail-fast so in-progress jobs don't get cancelled if one fails
      fail-fast: false
      matrix:
        include:
          - submodule: ${SUB_MODULE_PLACEHOLDER}
    steps:
      - name: Checkout from GitHub
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.DEPLOYMENT_ROLE_TO_ASSUME }}
          aws-region: ${{ env.TARGET_REGION }}
          role-duration-seconds: 3600

      - name: Terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: ${{ matrix.submodule }}
          label: ${{ matrix.submodule }}
        # GITHUB_TOKEN required for integration with dflook/terraform-apply
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
