name: Terraform fmt

on:
  pull_request:
    branches:
      - $default-branch
    paths:
      - '**.tf'

jobs:
  fmt:
    runs-on: ubuntu-latest
    name: terraform fmt
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - run: |
          git clone https://spghactions:${{secrets.SPGH_TOKEN}}@github.com/smartpension/.github .github/actions
          cd .github/actions
          git checkout shared-actions/1.3.0

      - uses: ./.github/actions/shared-actions/terraform-fmt

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "**/*.tf *.tf"
          commit_message: "Automated terraform fmt"
